apiVersion: v1
kind: Service
metadata:
  name: clientservice
  labels:
    run: clientservice
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    name: http
  - port: 443
    protocol: TCP
    name: https
  selector:
    run: clientservice
---
