apiVersion: v1
kind: Service
metadata:
  name: server
spec:
  type: LoadBalancer
  selector:
    app: server
  ports:
    - name: server_port
      protocol: TCP
      port: 80
      targetPort: 3333
    - name: rtmp_port
      protocol: TCP
      port: 80
      targetPort: 1935
    - name: stream_port 
      protocol: TCP
      port: 80
      targetPort: 8888