apiVersion: v1
kind: PersistentVolume            # Create a PersistentVolume
metadata:
  name: server-pv
  labels:
    type: local
spec:
  storageClassName: standard      # Storage class. A PV Claim requesting the same storageClass can be bound to this volume. 
  capacity:
    storage: 150Mi
  accessModes:
    - ReadWriteMany
  hostPath:                       # hostPath PersistentVolume is used for development and testing. It uses a file/directory on the Node to emulate network-attached storage
    path: "/mnt/data"
  persistentVolumeReclaimPolicy: Retain  # Retain the PersistentVolume even after PersistentVolumeClaim is deleted. The volume is considered “released”. But it is not yet available for another claim because the previous claimant’s data remains on the volume. 
---

apiVersion: v1
kind: PersistentVolumeClaim        # Create a PersistentVolumeClaim to request a PersistentVolume storage
metadata:                          # Claim name and labels
  name: server-pv-claim
  labels:
    app: server
spec:                              # Access mode and resource limits
  storageClassName: standard       # Request a certain storage class
  accessModes:
    - ReadWriteMany                # ReadWriteOnce means the volume can be mounted as read-write by a single Node
  resources:
    requests:
      storage: 250Mi
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: server-deployment
  labels:
    app: server
spec:
  replicas: 3
  selector:
    matchLabels:
      app: server
  template:
    metadata:
      labels:
        app: server

    spec:
      containers:
        - name: server
          image: timnuwa/server:latest
          ports:
            - containerPort: 8080
          env:
            - name: KEY1
              valueFrom:
                configMapKeyRef:
                  name: server-config
                  key: someKey1
            - name: NEXT_SERVICE
              valueFrom:
                configMapKeyRef:
                  name: server-config
                  key: nextService
            - name: SERVICE_API_KEY
              valueFrom:
                secretKeyRef:
                  name: server-secrets
                  key: service-api-key
            - name: USER_SERVICE
              valueFrom:
                configMapKeyRef:
                  name: server-config
                  key: userService
            - name: USER_SERVICE_PORT
              valueFrom:
                configMapKeyRef:
                  name: server-config
                  key: userServicePort
      volumes:                       # A PersistentVolume is mounted as a volume to the Pod  
      - name: server-persistent-storage
        persistentVolumeClaim:
          claimName: server-pv-claim