apiVersion: apps/v1
kind: Deployment
metadata:
  name: server-deployment
  labels:
    app: server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: server
  template:
    metadata:
      labels:
        app: server

    spec:
      containers:
        - name: server
          image: timnuwa/server:latest
          ports:
            - containerPort: 8888
          env:
            - name: KEY1
              valueFrom:
                configMapKeyRef:
                  name: server-config
                  key: someKey1
            